"use client";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {ReactNode,useEffect,useState} from "react";
import {ArrowRightStartOnRectangleIcon,BeakerIcon,BellIcon,ChartBarSquareIcon,CircleStackIcon,Cog6ToothIcon,ExclamationTriangleIcon,MagnifyingGlassIcon,SignalIcon,UsersIcon,XMarkIcon} from "@heroicons/react/24/outline";
import {api,clearSession,refreshToken,storedUser,token,type User} from "@/lib/api";
const workspaceNavigation=[["/operations","Live Operations",ChartBarSquareIcon],["/incidents","Incidents",ExclamationTriangleIcon],["/logs","Log Explorer",MagnifyingGlassIcon],["/system","System",Cog6ToothIcon]] as const;
const adminNavigation=[["/datasets","Datasets",CircleStackIcon],["/evaluation","Evaluation Lab",BeakerIcon],["/users","Users",UsersIcon]] as const;
export default function AppShell({children,title,subtitle,actions}:{children:ReactNode;title:string;subtitle:string;actions?:ReactNode}){
 const path=usePathname(),router=useRouter();const[user,setUser]=useState<User|null>(null),[menu,setMenu]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[unread,setUnread]=useState(true),[incidentCount,setIncidentCount]=useState(0);
 useEffect(()=>{if(!token()){router.replace("/login");return}setUser(storedUser());const expired=()=>router.replace("/login");const loadIncidents=()=>void api<any[]>("/incidents").then(items=>setIncidentCount(items.filter(item=>item.status!=="RESOLVED").length)).catch(()=>{});loadIncidents();window.addEventListener("rca:auth-expired",expired);window.addEventListener("rca:incidents-changed",loadIncidents);return()=>{window.removeEventListener("rca:auth-expired",expired);window.removeEventListener("rca:incidents-changed",loadIncidents)}},[router]);
 async function logout(){const refresh=refreshToken();try{if(refresh)await api("/auth/logout",{method:"POST",body:JSON.stringify({refresh_token:refresh})})}finally{clearSession();router.push("/login")}}
 const Navigation=({items}:{items:typeof workspaceNavigation|typeof adminNavigation})=><nav>{items.map(([href,label,Icon])=><Link key={href} className={path.startsWith(href)?"active":""} href={href} onClick={()=>setMenu(false)}><Icon/>{label}{href==="/incidents"&&incidentCount>0&&<em>{incidentCount}</em>}</Link>)}</nav>;
 return <div className="app">{menu&&<button className="sidebar-backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}<aside className={menu?"sidebar open":"sidebar"}><div className="sidebar-brand"><span><SignalIcon/></span><div>5G RCA<b>Copilot</b></div><button aria-label="Close navigation" onClick={()=>setMenu(false)}><XMarkIcon/></button></div><div className="nav-label">WORKSPACE</div><Navigation items={workspaceNavigation}/>{user?.role==="ADMIN"&&<><div className="nav-label">ADMINISTRATION</div><Navigation items={adminNavigation}/></>}<div className="sidebar-foot"><div className="health-pill"><span/>Application ready</div><button onClick={logout}><div className="avatar">{user?.name?.slice(0,2).toUpperCase()||"NA"}</div><span><b>{user?.name||"Network Analyst"}</b><small>{user?.role||"ANALYST"}</small></span><ArrowRightStartOnRectangleIcon/></button></div></aside>
 <main className="workspace"><header><button className="menu-btn" aria-label="Open navigation" onClick={()=>setMenu(!menu)}>☰</button><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions">{actions}<div className="notification-wrap"><button className="icon-btn" aria-label="Notifications" aria-expanded={notificationsOpen} onClick={()=>setNotificationsOpen(!notificationsOpen)}><BellIcon/>{unread&&<i/>}</button>{notificationsOpen&&<div className="notification-popover"><div><b>Notifications</b><button onClick={()=>setUnread(false)}>Mark all read</button></div><Link href="/incidents" onClick={()=>{setNotificationsOpen(false);setUnread(false)}}><span className="severity critical">INCIDENTS</span><p>{incidentCount} active incident{incidentCount===1?"":"s"} require investigation.</p></Link><Link href="/system" onClick={()=>{setNotificationsOpen(false);setUnread(false)}}><span className="severity warning">SYSTEM</span><p>Review optional OpenSearch and Ollama services.</p></Link></div>}</div></div></header>{children}</main></div>
}
