"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowPathIcon, ChevronRightIcon, DocumentMagnifyingGlassIcon, MagnifyingGlassIcon, PauseIcon, PlayIcon, PlusIcon, SparklesIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import AppShell from "./AppShell";
import Assistant from "./AssistantPanel";
import { api, fmt } from "@/lib/api";

export type NetworkLog = { log_id:string; "@timestamp":string; node:string; component:string; severity:string; message:string; trace_id:string; session_id:string; error_code:string; [key:string]:unknown };
type Filters = { node:string; component:string; severity:string; keyword:string; trace_id:string; session_id:string; error_code:string };
const EMPTY_FILTERS:Filters = { node:"", component:"", severity:"", keyword:"", trace_id:"", session_id:"", error_code:"" };

export default function LogWorkspace({ explorer=false }:{ explorer?:boolean }) {
  const [logs,setLogs]=useState<NetworkLog[]>([]), [summary,setSummary]=useState<any>(null), [selected,setSelected]=useState<Set<string>>(new Set()), [detail,setDetail]=useState<NetworkLog|null>(null);
  const [paused,setPaused]=useState(false), [loading,setLoading]=useState(true), [error,setError]=useState(""), [filters,setFilters]=useState<Filters>(EMPTY_FILTERS), [refreshKey,setRefreshKey]=useState(0);
  const [assistantOpen,setAssistantOpen]=useState(false), [analyzeRequest,setAnalyzeRequest]=useState(0), [datasets,setDatasets]=useState<any[]>([]), [datasetId,setDatasetId]=useState(""), [incidents,setIncidents]=useState<any[]>([]);
  const [actionMessage,setActionMessage]=useState(""), [actionBusy,setActionBusy]=useState(false);

  useEffect(()=>{ Promise.all([api<any[]>("/datasets"),api<any[]>("/incidents")]).then(([ds,ins])=>{setDatasets(ds);setIncidents(ins);if(ds[0])setDatasetId(ds[0].id)}).catch(e=>setError(e.message)); },[]);
  useEffect(()=>{ let active=true; const timer=window.setTimeout(async()=>{setLoading(true);setError("");try{const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const data=await api<any>(`/logs?limit=200&${query}`);if(active){setLogs(data.items);setSummary(data.summary)}}catch(e){if(active)setError(e instanceof Error?e.message:"Gagal memuat log")}finally{if(active)setLoading(false)}},filters.keyword?350:0);return()=>{active=false;clearTimeout(timer)} },[filters,refreshKey]);
  useEffect(()=>setSelected(new Set()),[filters]);
  useEffect(()=>{if(paused||explorer)return;let cancelled=false,source:EventSource|null=null,retry:number|undefined;const connect=async()=>{try{const{ticket}=await api<{ticket:string}>("/logs/stream-ticket",{method:"POST"});if(cancelled)return;source=new EventSource(`/api/logs/stream?ticket=${encodeURIComponent(ticket)}`);source.addEventListener("logs",event=>{const incoming=JSON.parse((event as MessageEvent).data) as NetworkLog[];setLogs(current=>[...incoming,...current.filter(row=>!incoming.some(next=>next.log_id===row.log_id))].slice(0,200))});source.onerror=()=>{source?.close();if(!cancelled)retry=window.setTimeout(connect,2000)}}catch(e){if(!cancelled){setError(e instanceof Error?e.message:"Live stream terputus");retry=window.setTimeout(connect,3000)}}};connect();return()=>{cancelled=true;source?.close();if(retry)clearTimeout(retry)}},[paused,explorer]);

  const selectedLogs=useMemo(()=>logs.filter(row=>selected.has(row.log_id)),[logs,selected]);
  const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
  function analyze(ids=[...selected]){if(!ids.length){setActionMessage("Pilih minimal satu log untuk dianalisis.");return}setSelected(new Set(ids));setAssistantOpen(true);setAnalyzeRequest(v=>v+1);setActionMessage(`${ids.length} log dikirim ke AI RCA Assistant.`)}
  async function findRelated(ids=[...selected]){if(!ids.length||actionBusy)return;setActionBusy(true);setError("");try{const bundle=await api<any>("/logs/search-related",{method:"POST",body:JSON.stringify({log_ids:ids,top_k:20,question:"Find causally related 5G network events"})});const related=bundle.evidence_logs as NetworkLog[];setLogs(related);setSelected(new Set(related.map(row=>row.log_id)));setActionMessage(`${related.length} related logs ditemukan dari ${bundle.candidate_count} kandidat.`);setDetail(null)}catch(e){setError(e instanceof Error?e.message:"Related logs gagal dicari")}finally{setActionBusy(false)}}
  async function createIncident(ids=[...selected]){if(!ids.length||actionBusy)return;const context=logs.filter(row=>ids.includes(row.log_id));setActionBusy(true);setError("");try{const item=await api<any>("/incidents",{method:"POST",body:JSON.stringify({title:`Investigation: ${[...new Set(context.map(row=>row.component))].join(" / ")} event`,description:`Created from ${ids.length} selected logs (${ids.join(", ")}).`,incident_timestamp:context[0]?.["@timestamp"]||new Date().toISOString(),severity:context.some(row=>row.severity==="CRITICAL")?"CRITICAL":"MAJOR",nodes:[...new Set(context.map(row=>row.node))],source_type:"MANUAL"})});setIncidents(current=>[item,...current]);window.dispatchEvent(new Event("rca:incidents-changed"));setActionMessage(`${item.incident_code} berhasil dibuat dari ${ids.length} log.`);setDetail(null)}catch(e){setError(e instanceof Error?e.message:"Incident gagal dibuat")}finally{setActionBusy(false)}}

  const actions=<><span className={explorer?"mode-badge":"live-badge"}><i/>{explorer?"SEARCH MODE":paused?"PAUSED":"LIVE"}</span>{!explorer&&<button className="secondary-btn" onClick={()=>setPaused(!paused)}>{paused?<PlayIcon/>:<PauseIcon/>}{paused?"Resume":"Pause"}</button>}<button className="icon-btn" aria-label="Refresh logs" onClick={()=>setRefreshKey(v=>v+1)}><ArrowPathIcon/></button><button className="secondary-btn mobile-ai-toggle" onClick={()=>setAssistantOpen(true)}><SparklesIcon/>Ask AI</button></>;
  return <AppShell title={explorer?"Log Explorer":"Live Operations"} subtitle={explorer?"Search and correlate historical 5G Core events":"Near-real-time 5G Core network observability"} actions={actions}>
    <div className="operations-layout"><section className="operations-main">
      {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>setRefreshKey(v=>v+1)}>Retry</button></div>}{actionMessage&&<div className="success-banner" role="status"><span>{actionMessage}</span><button onClick={()=>setActionMessage("")}>Dismiss</button></div>}
      <div className="filterbar"><select aria-label="Dataset" value={datasetId} onChange={e=>setDatasetId(e.target.value)}>{datasets.length?datasets.map(item=><option value={item.id} key={item.id}>{item.name}</option>):<option value="">Loading datasets…</option>}</select><FilterSelect label="Node" value={filters.node} values={["AMF-01","AMF-02","SMF-01","SMF-02","UPF-01","UPF-02"]} onChange={node=>setFilters({...filters,node})}/><FilterSelect label="Component" value={filters.component} values={["AMF","SMF","UPF"]} onChange={component=>setFilters({...filters,component})}/><FilterSelect label="Severity" value={filters.severity} values={["INFO","WARNING","ERROR","CRITICAL"]} onChange={severity=>setFilters({...filters,severity})}/><label className="search"><MagnifyingGlassIcon/><input aria-label="Search logs" placeholder="Search message or code…" value={filters.keyword} onChange={e=>setFilters({...filters,keyword:e.target.value})}/></label></div>
      {explorer&&<div className="explorer-filters"><input placeholder="Trace ID" value={filters.trace_id} onChange={e=>setFilters({...filters,trace_id:e.target.value})}/><input placeholder="Session ID" value={filters.session_id} onChange={e=>setFilters({...filters,session_id:e.target.value})}/><input placeholder="Error code" value={filters.error_code} onChange={e=>setFilters({...filters,error_code:e.target.value})}/><button className="secondary-btn" onClick={()=>setFilters(EMPTY_FILTERS)}>Clear filters</button></div>}
      <div className="metric-grid"><Metric label="Logs / minute" value={summary?.logs_per_minute??"—"} delta="current view" tone="blue"/><Metric label="Error rate" value={`${summary?.error_rate??0}%`} delta="error + critical" tone="red"/><Metric label="Warning rate" value={`${summary?.warning_rate??0}%`} delta="current window" tone="amber"/><Metric label="Active incidents" value={incidents.filter(i=>i.status!=="RESOLVED").length} delta={`${incidents.filter(i=>i.severity==="CRITICAL"&&i.status!=="RESOLVED").length} critical`} tone="purple"/></div>
      <div className="chart-card"><div className="card-head"><div><h3>Event volume</h3><span>Logs and errors over time</span></div><div className="legend"><span><i className="cyan"/>Logs</span><span><i className="red"/>Errors</span></div></div><ResponsiveContainer width="100%" height={190}><AreaChart data={summary?.timeline||[]}><defs><linearGradient id="logs" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#14b8a6" stopOpacity={.35}/><stop offset="95%" stopColor="#14b8a6" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#233044"/><XAxis dataKey="time" stroke="#718096" tickLine={false}/><YAxis stroke="#718096" tickLine={false}/><Tooltip contentStyle={{background:"#101827",border:"1px solid #29364a",borderRadius:8}}/><Area type="monotone" dataKey="total" stroke="#18c7b5" fill="url(#logs)" strokeWidth={2}/><Area type="monotone" dataKey="errors" stroke="#fb6470" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>
      <div className="logs-card"><div className="card-head"><div><h3>{explorer?"Search results":"Live log stream"}</h3><span>{logs.length} events in current view</span></div>{selected.size>0&&<div className="selection-bar"><b>{selected.size} selected</b><button disabled={actionBusy} onClick={()=>analyze()}>Analyze with AI</button><button disabled={actionBusy} onClick={()=>findRelated()}><DocumentMagnifyingGlassIcon/>Related</button><button disabled={actionBusy} onClick={()=>createIncident()}><PlusIcon/>Incident</button><button onClick={()=>setSelected(new Set())}>Clear</button></div>}</div><div className="table-wrap"><table className="log-table"><thead><tr><th><input aria-label="Select all logs" type="checkbox" checked={logs.length>0&&selected.size===logs.length} onChange={e=>setSelected(e.target.checked?new Set(logs.map(row=>row.log_id)):new Set())}/></th><th>Timestamp</th><th>Node</th><th>Component</th><th>Severity</th><th>Message</th><th>Trace ID</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={8} className="empty"><div className="spinner"/>Loading logs…</td></tr>:logs.length===0?<tr><td colSpan={8} className="empty">No logs match the active filters.</td></tr>:logs.map(log=><tr key={log.log_id} className={selected.has(log.log_id)?"selected":""}><td><input aria-label={`Select ${log.log_id}`} type="checkbox" checked={selected.has(log.log_id)} onChange={()=>toggle(log.log_id)}/></td><td className="mono">{fmt(log["@timestamp"])}</td><td><b>{log.node}</b></td><td><span className="component">{log.component}</span></td><td><span className={`severity ${log.severity.toLowerCase()}`}>{log.severity}</span></td><td className="message" onClick={()=>setDetail(log)}>{log.message}</td><td className="mono muted">{log.trace_id}</td><td><button aria-label={`Open ${log.log_id}`} className="row-open" onClick={()=>setDetail(log)}><ChevronRightIcon/></button></td></tr>)}</tbody></table></div></div>
    </section><Assistant open={assistantOpen} onClose={()=>setAssistantOpen(false)} selected={selectedLogs} filters={filters} analyzeRequest={analyzeRequest} onEvidence={log=>setDetail(log as NetworkLog)}/></div>
    {detail&&<div className="drawer-overlay" onClick={()=>setDetail(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button aria-label="Close log detail" className="drawer-close" onClick={()=>setDetail(null)}><XMarkIcon/></button><span className={`severity ${detail.severity.toLowerCase()}`}>{detail.severity}</span><h2>{detail.node} · {detail.component}</h2><p className="drawer-message">{detail.message}</p><div className="drawer-actions"><button className="primary-small" onClick={()=>{analyze([detail.log_id]);setDetail(null)}}><SparklesIcon/>Analyze with AI</button><button className="secondary-btn" onClick={()=>findRelated([detail.log_id])}><DocumentMagnifyingGlassIcon/>Related logs</button><button className="secondary-btn" onClick={()=>createIncident([detail.log_id])}><PlusIcon/>Create incident</button></div><dl>{[["Timestamp",detail["@timestamp"]],["Log ID",detail.log_id],["Trace ID",detail.trace_id],["Session ID",detail.session_id],["Error code",detail.error_code||"—"]].map(([label,value])=><div key={String(label)}><dt>{String(label)}</dt><dd>{String(value)}</dd></div>)}</dl><h4>Raw JSON</h4><pre>{JSON.stringify(detail,null,2)}</pre></aside></div>}
  </AppShell>;
}
function FilterSelect({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(value:string)=>void}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">All {label.toLowerCase()}</option>{values.map(item=><option key={item}>{item}</option>)}</select>}
function Metric({label,value,delta,tone}:{label:string;value:string|number;delta:string;tone:string}){return <div className={`metric ${tone}`}><span>{label}</span><div><b>{value}</b><em>{delta}</em></div><i/></div>}
