"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {api,saveSession,token} from "@/lib/api";
import {BoltIcon,CheckCircleIcon,SignalIcon} from "@heroicons/react/24/outline";
export default function Login(){
 const router=useRouter();const[email,setEmail]=useState("admin@5grca.local");const[password,setPassword]=useState("admin123");const[error,setError]=useState("");const[loading,setLoading]=useState(false);
 useEffect(()=>{if(token())router.replace("/operations")},[router]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const result=await api<any>("/auth/login",{method:"POST",body:JSON.stringify({email,password})});saveSession(result);router.push("/operations")}catch(err){setError(err instanceof Error?err.message:"Login failed")}finally{setLoading(false)}}
 return <main className="login-page"><section className="login-brand"><div className="brand-lockup"><span className="brand-mark"><SignalIcon/></span><span>5G RCA <b>Copilot</b></span></div><div className="hero-copy"><div className="eyebrow"><span/> AI-ASSISTED OBSERVABILITY</div><h1>See the signal.<br/><em>Find the cause.</em></h1><p>Investigate 5G network incidents with traceable hybrid retrieval and evidence-grounded RCA.</p><div className="features"><span><CheckCircleIcon/>Near-real-time monitoring</span><span><CheckCircleIcon/>BM25 + semantic retrieval</span><span><CheckCircleIcon/>Evidence-grounded RCA</span></div></div><div className="network-grid"><i/><i/><i/><i/><i/><i/></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div className="mobile-brand"><SignalIcon/> 5G RCA Copilot</div><div className="login-icon"><BoltIcon/></div><h2>Welcome back</h2><p>Sign in to the network operations workspace</p><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn" disabled={loading}>{loading?"Signing in…":"Sign in to workspace"}</button><div className="demo-box"><b>Demo credentials</b><span>admin@5grca.local · admin123</span></div></form><small>Synthetic data only · Secure local workspace</small></section></main>
}
