"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowPathIcon, MagnifyingGlassIcon, PlusIcon, XMarkIcon } from "@heroicons/react/24/outline";
import AppShell from "@/components/AppShell";
import { api, fmt } from "@/lib/api";

type Incident={id:string;incident_code:string;title:string;description:string;incident_timestamp:string;severity:string;status:string;source_type:string;nodes:string[];updated_at:string};
const initialForm={title:"",description:"",severity:"MAJOR",status:"NEW",source_type:"MANUAL",node:"SMF-01",incident_timestamp:""};

export default function Incidents(){
 const[items,setItems]=useState<Incident[]>([]),[show,setShow]=useState(false),[selected,setSelected]=useState<Incident|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[query,setQuery]=useState(""),[severity,setSeverity]=useState(""),[status,setStatus]=useState(""),[source,setSource]=useState(""),[form,setForm]=useState(initialForm);
 async function load(){setLoading(true);setError("");try{setItems(await api<Incident[]>("/incidents"))}catch(e){setError(e instanceof Error?e.message:"Incidents could not be loaded")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>items.filter(item=>(!query||`${item.incident_code} ${item.title} ${item.description} ${item.nodes.join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(!severity||item.severity===severity)&&(!status||item.status===status)&&(!source||item.source_type===source)),[items,query,severity,status,source]);
 async function create(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const item=await api<Incident>("/incidents",{method:"POST",body:JSON.stringify({title:form.title,description:form.description,severity:form.severity,status:form.status,source_type:form.source_type,nodes:[form.node],incident_timestamp:form.incident_timestamp?new Date(form.incident_timestamp).toISOString():new Date().toISOString()})});setItems(current=>[item,...current]);window.dispatchEvent(new Event("rca:incidents-changed"));setMessage(`${item.incident_code} was created.`);setShow(false);setForm(initialForm)}catch(e){setError(e instanceof Error?e.message:"The incident could not be created")}finally{setSaving(false)}}
 async function updateStatus(item:Incident,nextStatus:string){setSaving(true);setError("");try{const updated=await api<Incident>(`/incidents/${item.id}`,{method:"PATCH",body:JSON.stringify({status:nextStatus})});setItems(current=>current.map(row=>row.id===updated.id?updated:row));setSelected(current=>current?.id===updated.id?updated:current);window.dispatchEvent(new Event("rca:incidents-changed"));setMessage(`${updated.incident_code} was updated to ${updated.status}.`)}catch(e){setError(e instanceof Error?e.message:"The incident status could not be updated")}finally{setSaving(false)}}
 return <AppShell title="Incidents" subtitle="Investigate and track network events" actions={<><button className="icon-btn" aria-label="Refresh incidents" onClick={load}><ArrowPathIcon/></button><button className="primary-small" onClick={()=>setShow(true)}><PlusIcon/>Create incident</button></>}>
  <div className="page-content">{error&&<div className="error-banner"><span>{error}</span><button onClick={load}>Retry</button></div>}{message&&<div className="success-banner"><span>{message}</span><button onClick={()=>setMessage("")}>Dismiss</button></div>}
   <div className="page-toolbar incident-toolbar"><label className="search"><MagnifyingGlassIcon/><input aria-label="Search incidents" placeholder="Search incident, node, or description…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={severity} label="severity" values={["INFO","WARNING","MAJOR","CRITICAL"]} onChange={setSeverity}/><Select value={status} label="status" values={["NEW","INVESTIGATING","ANALYZED","RESOLVED"]} onChange={setStatus}/><Select value={source} label="source" values={["MANUAL","ANOMALY","FORECAST","ANOMALY_FORECAST"]} onChange={setSource}/><button className="secondary-btn" onClick={()=>{setQuery("");setSeverity("");setStatus("");setSource("")}}>Clear</button></div>
   <div className="panel"><table className="data-table incident-table"><thead><tr><th>Incident ID</th><th>Timestamp</th><th>Title</th><th>Nodes</th><th>Severity</th><th>Source</th><th>Status</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={8} className="empty"><div className="spinner"/>Loading incidents…</td></tr>:filtered.length===0?<tr><td colSpan={8} className="empty">No incidents match the active filters.</td></tr>:filtered.map(item=><tr key={item.id} onClick={()=>setSelected(item)}><td className="accent">{item.incident_code}</td><td className="mono">{fmt(item.incident_timestamp)}</td><td><b>{item.title}</b><small>{item.description}</small></td><td>{item.nodes.join(", ")||"—"}</td><td><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span></td><td>{item.source_type}</td><td onClick={e=>e.stopPropagation()}><select className="table-select" value={item.status} disabled={saving} onChange={e=>updateStatus(item,e.target.value)}>{["NEW","INVESTIGATING","ANALYZED","RESOLVED"].map(value=><option key={value}>{value}</option>)}</select></td><td>›</td></tr>)}</tbody></table></div>
  </div>
  {show&&<div className="modal-overlay" onClick={()=>setShow(false)}><form className="modal incident-form" onSubmit={create} onClick={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setShow(false)}><XMarkIcon/></button><h2>Create incident</h2><p>Record a network event for investigation and AI analysis.</p><label>Title<input required minLength={3} maxLength={255} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Example: PDU session failure spike"/></label><label>Description<textarea maxLength={5000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe the observed symptoms…"/></label><div className="form-grid"><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{["INFO","WARNING","MAJOR","CRITICAL"].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["NEW","INVESTIGATING","ANALYZED","RESOLVED"].map(x=><option key={x}>{x}</option>)}</select></label><label>Source<select value={form.source_type} onChange={e=>setForm({...form,source_type:e.target.value})}>{["MANUAL","ANOMALY","FORECAST","ANOMALY_FORECAST"].map(x=><option key={x}>{x}</option>)}</select></label><label>Node<select value={form.node} onChange={e=>setForm({...form,node:e.target.value})}>{["AMF-01","AMF-02","SMF-01","SMF-02","UPF-01","UPF-02"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Incident time<input type="datetime-local" value={form.incident_timestamp} onChange={e=>setForm({...form,incident_timestamp:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setShow(false)}>Cancel</button><button className="primary-small" disabled={saving}>{saving?"Creating…":"Create incident"}</button></div></form></div>}
  {selected&&<div className="drawer-overlay" onClick={()=>setSelected(null)}><aside className="drawer incident-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}><XMarkIcon/></button><span className={`severity ${selected.severity.toLowerCase()}`}>{selected.severity}</span><h2>{selected.incident_code}</h2><h3>{selected.title}</h3><p className="drawer-message">{selected.description}</p><dl>{[["Timestamp",new Date(selected.incident_timestamp).toLocaleString("en-GB")],["Nodes",selected.nodes.join(", ")],["Source",selected.source_type],["Last update",new Date(selected.updated_at).toLocaleString("en-GB")]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><label className="drawer-status">Investigation status<select value={selected.status} disabled={saving} onChange={e=>updateStatus(selected,e.target.value)}>{["NEW","INVESTIGATING","ANALYZED","RESOLVED"].map(x=><option key={x}>{x}</option>)}</select></label></aside></div>}
 </AppShell>
}
function Select({value,label,values,onChange}:{value:string;label:string;values:string[];onChange:(value:string)=>void}){return <select aria-label={`Filter by ${label}`} value={value} onChange={e=>onChange(e.target.value)}><option value="">All {label}</option>{values.map(x=><option key={x}>{x}</option>)}</select>}
